<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="PermissionTypes.aspx.cs" Inherits="WebApplication1.PermissionTypes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col">
            <h3>Permission Types</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <asp:Button CssClass="btn btn-primary" runat="server" ID="newPermission" OnClick="newPermission_Click" Text="New Permission Type" PostBackUrl="~/NewPermissionType.aspx" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col">
            <asp:GridView ID="GridView1" runat="server" ItemType="TestEntities.PermissionTypeEntity" DataKeyNames="Id"  OnRowDataBound="GridView1_RowDataBound"
                SelectMethod="GridView1_GetData" UpdateMethod="GridView1_UpdateItem" DeleteMethod="GridView1_DeleteItem" 
                AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" 
                AutoGenerateColumns="false">
                <Columns>
                    <asp:DynamicField DataField="Id"  ItemStyle-Width="50px" />
                    <asp:DynamicField DataField="Description" ItemStyle-Width="250px" />
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
